# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 367, 212))
        self.groupBox_10.setObjectName("groupBox_10")
        self.result = QtWidgets.QLabel(self.groupBox_10)
        self.result.setGeometry(QtCore.QRect(10, 140, 351, 71))
        self.result.setText("")
        self.result.setObjectName("result")
        self.Q2_1 = QtWidgets.QPushButton(self.groupBox_10)
        self.Q2_1.setGeometry(QtCore.QRect(10, 20, 131, 23))
        self.Q2_1.setObjectName("Q2_1")
        self.Q2_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.Q2_2.setGeometry(QtCore.QRect(10, 50, 131, 23))
        self.Q2_2.setObjectName("Q2_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_5.setGeometry(QtCore.QRect(150, 10, 131, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 111, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.img_idx = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.img_idx.setMinimum(1)
        self.img_idx.setMaximum(15)
        self.img_idx.setObjectName("img_idx")
        self.verticalLayout.addWidget(self.img_idx)
        self.Q2_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Q2_3.setObjectName("Q2_3")
        self.verticalLayout.addWidget(self.Q2_3)
        self.Q2_4 = QtWidgets.QPushButton(self.groupBox_10)
        self.Q2_4.setGeometry(QtCore.QRect(10, 80, 131, 23))
        self.Q2_4.setObjectName("Q2_4")
        self.Q2_5 = QtWidgets.QPushButton(self.groupBox_10)
        self.Q2_5.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.Q2_5.setObjectName("Q2_5")
        self.Q2_1.raise_()
        self.Q2_2.raise_()
        self.groupBox_5.raise_()
        self.Q2_4.raise_()
        self.Q2_5.raise_()
        self.result.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IPCVDL HW2 Q2"))
        self.groupBox_10.setTitle(_translate("MainWindow", "2. Calibration"))
        self.Q2_1.setText(_translate("MainWindow", "2.1 Corner Detection"))
        self.Q2_2.setText(_translate("MainWindow", "2.2 Intrinsic Matrix"))
        self.groupBox_5.setTitle(_translate("MainWindow", "2.3 Extrinsic Matrix"))
        self.label.setText(_translate("MainWindow", "Select Image:"))
        self.Q2_3.setText(_translate("MainWindow", "2.3 Extrinsic Matrix"))
        self.Q2_4.setText(_translate("MainWindow", "2.4 Distortion Matrix"))
        self.Q2_5.setText(_translate("MainWindow", "2.5 Undistorted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
